title: Ian Vanhoof
email: ian@ianvanhoof.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is for me to think outload about things like design, coding the web, html, css and such.
baseurl: ""
url: "https://ianvanhoof.github.io" 
permalink           : date


# Build settings
plugins_dir:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - post_template.md
   - background_stripes_black.ai
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
